/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\gbdk\_emu\gameboytiledesigner22\background\backgroundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundampWidth 32
#define backgroundampHeight 18
#define backgroundampBank 0

extern unsigned char backgroundamp[];

/* End of BACKGROUNDMAP.H */
